# This file is used to generate config.earc, which controls archiving
# of ESMF member data.  The scripts that do that archiving are not in
# this public release, so this file is ignored.
config_earc:
  filename: config.earc
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.earc ##########
    # Ensemble archive specific
    
    echo "BEGIN: config.earc"
    
    # Get task specific resources
    . $EXPDIR/config.resources earc
    
    export NMEM_EARCGRP={doc.data_assimilation.NMEM_EARCGRP}
    
    export EARC_CYC="{tools.join(doc.archiving.EARC_CYC,' ')}" # Archive ensemble restarts at EARC_CYC only; can be "00 06 12 18"
    
    echo "END: config.earc"
    
