# This file is used to generate config.eobs, which would be used to
# control the ensemble observation innovation.  The code and scripts
# for that are not part of this public release, so this file is
# ignored.

config_eobs:
  filename: config.eobs
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.eobs config.eomg ##########
    # Ensemble innovation specific, dependency config.anal
    
    echo "BEGIN: config.eobs"
    
    # Get task specific resources
    . $EXPDIR/config.resources eobs
    
    export INVOBSSH="$HOMEgsi/scripts/exglobal_innovate_obs_fv3gfs.sh.ecf"
    export ENKFINVOBSSH="$HOMEgsi/scripts/exglobal_enkf_innovate_obs_fv3gfs.sh.ecf"
    export NMEM_EOMGGRP={doc.data_assimilation.NMEM_EOMGGRP}
    export RERUN_EOMGGRP="{tools.YES_NO(doc.data_assimilation.RERUN_EOMGGRP)}"
    #export USE_RADSTAT="NO" # This can be only used when bias correction is non-zero.
    export npe_gsi=$npe_eobs
    export nth_gsi={doc.nodes.omp_threads_for(doc.resources.run_eobs[0])}
    
    # GSI namelist options related to observer for EnKF
    export OBSINPUT_INVOBS="dmesh(1)=225.0,dmesh(2)=225.0"
    export OBSQC_INVOBS="tcp_width=60.0,tcp_ermin=2.0,tcp_ermax=12.0"
    
    echo "END: config.eobs"
    
