# This file is used to generate config.epos, which would be used to
# control the ENKF post-processing.  The scripts and code for the ENKF
# are not provided in this release, so this config file is ignored.

config_epos:
  filename: config.epos
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.epos ##########
    # Ensemble post processing specific
    
    echo "BEGIN: config.epos"
    
    # Get task specific resources
    . $EXPDIR/config.resources epos
    
    export ENKFPOSTSH="$HOMEgsi/scripts/exglobal_enkf_post_fv3gfs.sh.ecf"
    export nth_epos={doc.nodes.omp_threads_for(doc.resources.run_epos[0])}
    
    echo "END: config.epos"
    
